In [100]:
import pandas

raw_data = pandas.DataFrame(pandas.read_csv('F1.csv'),columns=['HomeTeam','AwayTeam','FTHG','FTAG'])
raw_data['HomeTeam'].unique()

array(['Monaco', 'Marseille', 'Angers', 'Brest', 'Dijon', 'Montpellier',
       'Nice', 'Lille', 'Strasbourg', 'Paris SG', 'Lyon', 'Nantes',
       'Amiens', 'Bordeaux', 'Metz', 'Nimes', 'Toulouse', 'St Etienne',
       'Reims', 'Rennes'], dtype=object)

In [97]:
def get_team_goals(team_name):
    import pandas
    # Store the raw data
    raw_data = pandas.DataFrame(pandas.read_csv('F1.csv'),columns=['HomeTeam','AwayTeam','FTHG','FTAG'])
    home_results = raw_data.groupby(['HomeTeam']).get_group(team_name)
    away_results = raw_data.groupby(['AwayTeam']).get_group(team_name)
    home_results.insert(1,'_TeamGoals',home_results['FTHG'])
    away_results.insert(1,'_TeamGoals',away_results['FTAG'])
    # All results sorted by index
    all_results = home_results.append(away_results).sort_index()
    return all_results['_TeamGoals'].values

In [98]:
get_team_goals('Paris SG')

array([3, 1, 4, 2, 1, 1, 0, 1, 4, 4, 4, 1, 2, 2, 2, 3, 4, 4, 3, 4, 2, 5,
       2, 4, 4, 4, 4], dtype=int64)

In [99]:
get_team_goals('Monaco')

array([0, 0, 2, 2, 3, 0, 3, 4, 1, 3, 1, 0, 1, 1, 2, 3, 0, 5, 3, 1, 1, 1,
       1, 2, 1, 1, 1, 1], dtype=int64)

In [102]:
import numpy as np
np.average(get_team_goals('Paris SG'))

2.7777777777777777

In [115]:
np.average(get_team_goals('Nantes'))

1.0

In [116]:
get_team_goals('Nantes')

array([1, 0, 2, 1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 1, 2, 0, 1, 1, 1, 2, 0, 2,
       1, 3, 0, 3, 0, 0], dtype=int64)